const https = require('https');
const fs = require('fs');
const path = require('path');

function downloadAndEncode(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return downloadAndEncode(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error('Failed to fetch ' + url + ': ' + res.statusCode));
      }
      const data = [];
      res.on('data', chunk => data.push(chunk));
      res.on('end', () => {
        const buffer = Buffer.concat(data);
        resolve(buffer.toString('base64'));
      });
    }).on('error', reject);
  });
}

(async () => {
  try {
    console.log('Downloading Sarabun-Regular...');
    const regular = await downloadAndEncode('https://github.com/google/fonts/raw/main/ofl/sarabun/Sarabun-Regular.ttf');
    console.log('Downloading Sarabun-Bold...');
    const bold = await downloadAndEncode('https://github.com/google/fonts/raw/main/ofl/sarabun/Sarabun-Bold.ttf');
    
    const targetPath = path.join(__dirname, 'src', 'assets', 'fonts.ts');
    const content = `// Auto-generated by download_fonts.js\nexport const SarabunRegular = '${regular}';\nexport const SarabunBold = '${bold}';\n`;
    fs.writeFileSync(targetPath, content);
    console.log('Successfully saved to ' + targetPath);
  } catch (err) {
    console.error('Error downloading fonts:', err);
    process.exit(1);
  }
})();
